- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  become: yes

- name: Add autonomoustuff-public.list
  file:
    path: /etc/apt/sources.list.d/autonomoustuff-public.list
    owner: root
    group: root
    mode: 0644
    state: touch
  become: yes

- name: Get lsb release
  shell: lsb_release -sc
  register: lsb_release

- name: Add AS public repo
  lineinfile:
    path: /etc/apt/sources.list.d/autonomoustuff-public.list
    line: 'deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ {{ lsb_release.stdout }} main'
    state: present
  become: yes

- name: Add kvaser library repo
  apt_repository:
    repo: ppa:jwhitleyastuff/kvaser-linux
  become: yes

- name: Install kvaser library
  become: yes
  apt:
    name:
      - kvaser-canlib-dev
      - kvaser-drivers-dkms
    update_cache: yes

- name: Install AS public modules
  become: yes
  apt:
    name:
      - libas-common
      - ros-{{ rosdistro }}-pacmod3
      - ros-{{ rosdistro }}-kvaser-interface
    update_cache: yes
