/**:
  ros__parameters:
    path: autoware
    discard:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: discard
      analyzers:
        speaker:
          type: 'diagnostic_aggregator/DiscardAnalyzer'
          path: speaker
          contains: [": speaker"]
        joystick:
          type: 'diagnostic_aggregator/DiscardAnalyzer'
          path: joystick
          contains: [": Joystick"]
