/**:
  ros__parameters:
    path: autoware
    control:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: control
      analyzers:
        topic_status:
          type: 'diagnostic_aggregator/GenericAnalyzer'
          path: topic_status
          contains: [": control_topic_status"]
          num_items: 0
