/**:
  ros__parameters:
    path: autoware
    map:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: map
      analyzers:
        topic_status:
          type: 'diagnostic_aggregator/GenericAnalyzer'
          path: topic_status
          contains: [": map_topic_status"]
          num_items: 0
