/**:
  ros__parameters:
    path: autoware
    vehicle:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: vehicle
      analyzers:
        topic_status:
          type: 'diagnostic_aggregator/GenericAnalyzer'
          path: topic_status
          contains: [": vehicle_topic_status"]
          num_items: 0
        vehicle_mcu_connection:
          type: 'diagnostic_aggregator/GenericAnalyzer'
          path: vehicle_mcu_connection
          contains: [": vehicle_mcu_connection"]
          num_items: 0
